# Generated by Django 2.0.7 on 2018-07-09 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemName', models.CharField(max_length=100)),
                ('ItemId', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('UPC', models.CharField(max_length=50)),
                ('NDC', models.CharField(max_length=50)),
                ('ItemDes', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabelName', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier', models.CharField(max_length=100)),
                ('SuppId', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('ContactName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Fax', models.CharField(blank=True, max_length=50, null=True)),
                ('Street', models.CharField(blank=True, max_length=150, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('ZipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('AccountNum', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Url', models.TextField(blank=True, max_length=200, null=True)),
                ('SupplierDes', models.TextField(blank=True, null=True)),
                ('Other', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('WareId', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('Warehouse', models.CharField(max_length=100)),
                ('WareCode', models.CharField(max_length=100)),
                ('External', models.BooleanField()),
                ('ContactName', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=10)),
                ('Fax', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('WarehouseDes', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
