# Generated by Django 2.0.7 on 2018-07-09 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.AddField(
            model_name='brand',
            name='BrandId',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
