# Generated by Django 2.0.7 on 2018-07-09 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0002_auto_20180708_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Label',
            fields=[
                ('LabelName', models.CharField(max_length=100)),
                ('LabelId', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Statu',
        ),
        migrations.RemoveField(
            model_name='label',
            name='id',
        ),
        migrations.AddField(
            model_name='label',
            name='LabelId',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
