# Generated by Django 2.0.7 on 2018-07-09 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0003_auto_20180709_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statu',
            name='id',
        ),
        migrations.AddField(
            model_name='statu',
            name='StatusId',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='DefaultLeadTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
