# Generated by Django 2.0.7 on 2018-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0004_auto_20180709_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
