# Generated by Django 2.0.7 on 2018-07-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0005_supplier_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='Status',
            new_name='Enable',
        ),
    ]
