# Generated by Django 2.0.7 on 2018-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0006_auto_20180709_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='Enable',
            field=models.BooleanField(default=True),
        ),
    ]
