# Generated by Django 2.0.7 on 2018-07-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManage', '0007_auto_20180709_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='DefaultLeadTime',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
